pipeline {
    agent any 
    stages {
        stage('Static Analysis') {
            steps {
                echo 'Run the static  to the ' 
            }
        }
        stage('Compile') {
            steps {
                echo 'Compile the source code' 
            }
        }
        stage('Security Check') {
            steps {
                echo 'Run the security check against the application' 
            }
        }
        stage('Run Unit Tests') {
            steps {
                echo 'Run unit tests from the source code' 
            }
        }
        stage('Run Integration Tests') {
            steps {
                echo 'PRESIDENT SIRF LANISH HONA CHAIYE' 
            }
        }
        stage('Publish Artifacts') {
            steps {
                echo 'YEH SKDC KARTA KYA HAI' 
            }
        }
    }
}
